### ISSUE TITLE
Unable to resolve relative paths

### ISSUE THREAD

**Issue by antonycourtney** [jquense/react-bootstrap-modal#1]
I'm trying to use react-bootstrap-modal in my project.

I installed with:

```sh
$ npm install --save react-bootstrap-modal
```

am importing with:

```javascript
var Modal = require('react-bootstrap-modal');
```

Attempting to build my project using webpack 1.7.3.  I get the error:

```
ERROR in ./~/react-bootstrap-modal/lib/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Modal in /Users/antony/home/src/chrome-extensions/tabman/node_modules/react-bootstrap-modal/lib
 @ ./~/react-bootstrap-modal/lib/index.js 2:17-39
```  

It looks to me `require` is correctly reading `./node_modules/react-bootstrap-modal/package.json` and following that to read `./node_modules/react-bootstrap-modal/lib/index.js` but then choking on relative path `"./lib/Modal"` in that file.

Apologies if this issue is arcane to my build setup.  Have you or others have used react-boostrap-modal in other webpack-based projects?  If so a pointer to a github repo so that I can compare that config with mine would be much appreciated.

**Comment by jquense** [comment]
no issue on your end just a dumb mistake on mine. fixed and published. version `1.0.2` should work just fine for you

**Comment by antonycourtney** [comment]
Confirmed this does work.  Thanks for the quick fix!
