### ISSUE TITLE
Is `animate` property is obsolete?

### ISSUE THREAD

**Issue by jesenko** [jquense/react-bootstrap-modal#10]
I tried disabling animation by setting `animate: false` on modal as demonstrated in README.md, however the fade-in and translate animation were still active.

After inspecting in source code, I could not found any usage of `animate` property (except it being listed in `propTypes` list). Is it considered obsolete? If so, readme should probably be updated accordingly...

Setting `transition: false` disabled the animation - hovewer, some additional styling is then needed in adition to `rbm-complete` to set the opacity of backdrop...

If it is in fact obsolete, I can open a PR updating the readme (and cleanning up obsolete probTypes)..

**Comment by jquense** [comment]
Hi there,

sorry for the lack of documentation there. `animate` controls whether `static` backdrops shaked when you try and close the modal by clicking outside it. `transition=false` disables the slide in/out when opening or closing

**Comment by jesenko** [comment]
Hm I just tried setting `animate=false`, however the shake animation was still activated when clicked outside modal... What disabled shake animation for me was setting `attentionAnimation: false`...

**Comment by hu9o** [comment]
I find this property to be poorly named... What about something like ``tryCloseStaticAnimation``?
It may be too verbose, but OTOH ``animation`` seems way too general and prone to confusion.
