### ISSUE TITLE
display: none on Modal.

### ISSUE THREAD

**Issue by datermine** [jquense/react-bootstrap-modal#12]
Hello! I'm having an issue where the transparent backdrop is being displayed, but the modal content itself is not. It's not being displayed because .modal {} has a display: none attribute and it is not being overriden. Please see attached screenshot. I'm using bootstrap 3.3.5.

<img width="1439" alt="screen shot 2015-12-17 at 9 44 04 am" src="https://cloud.githubusercontent.com/assets/286251/11872435/37f50652-a4a3-11e5-851f-a286555c9f5f.png">

**Comment by datermine** [comment]
hmm. It's possible I'm missing the transtion.js file for bootstrap. Will report back.

**Comment by gertig** [comment]
Did you see this note? "if you are using bootstrap and don't want to re-include styles you can just use /lib/styles/rbm-patch.css"

rbm-patch.css adds display: block; to the modal.

**Comment by manodupont** [comment]
What if I am actually using bootstrap.css coming form there in my app : 

```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css">
    <!--&lt;!&ndash; Optional theme &ndash;&gt;-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap-theme.min.css">
```

And still, the display: block doesnt show up when needed ?

**Comment by peebles** [comment]
I agree with manodupont above.  I've had to manually add the following to my own css files to get the dialog to show:

    .modal-open .modal {
      display: block;
    }

**Comment by peebles** [comment]
Oops, please ignore my comments here.  Once I *properly* included rbm-patch.css, things work properly.
