### ISSUE TITLE
onTransition handlers not fired

### ISSUE THREAD

**Issue by Nierrrrrrr** [jquense/react-bootstrap-modal#15]
onTransitionIn
onTransitionedIn
onTransitionOut
onTransitionedOut

These 4 event handlers of Modal are not fired when they should according to the description.

**Comment by rudeworks** [comment]
Also experiencing this issue, would really come in handy.

**Comment by uschmann** [comment]
Same issue here.
I need to focus an input field after the modal has opened.
As a workaround i set a timeout and select the input field.
But this solution seems really hacky.

I tested it on OSX chrome Version 51.0.2704.63 (64-bit)

**Comment by jquense** [comment]
looks like a bug when we switched underlying implementations. the new modal takes the callbacks fired by react-overlays modal which are

onEnter
onEntering
onEntered

onExit
onExiting
onExited

If someone wants to confirm those work and/or PR a doc fix I'd be most appreciative

**Comment by jquense** [comment]
Oops looks like they aren't passed through either.  I'll fix when I get a moment, PR's gladly accepted

**Comment by peebles** [comment]
Hey, I need these callbacks to work.  Its been a while since the original bug report ...

**Comment by jquense** [comment]
PR's welcome!

**Comment by Nierrrrrrr** [comment]
I think this issue is resolved by #17, thanks to @peebles.

**Comment by patotoma** [comment]
I'm experiencing this issue with version 4.0.0
