### ISSUE TITLE
control width 

### ISSUE THREAD

**Issue by rpedela** [jquense/react-bootstrap-modal#16]
Is it possible to control the width of the modal using a property? If so, how? I use this module in several places and the default behavior is fine, but I have one case where I need a narrow modal.

**Comment by jehartzog** [comment]
I had the same question, looked at the source code and found out how to do it.
```
<Modal dialogClassName='modal-lg' show={this.state.showModal} onHide={this.closeModal}>
```
If the author asks me to create a PR to update the documentation I'd be happy to do so.
