### ISSUE TITLE
Using refs inside components doesn't work

### ISSUE THREAD

**Issue by larzconwell** [jquense/react-bootstrap-modal#2]
I have the following snippet inside a render:
```
<Modal show={this.state.open} onHide={closeModal} aria-labelledby="ModalHeader">
    <Modal.Header closeButton>
        <Modal.Title id="ModalHeader">This shouldn't be as ugly</Modal.Title>
    </Modal.Header>
    <Modal.Body>
        <input type="text" ref="input" />
    </Modal.Body>
    <Modal.Footer>
        <Modal.Dismiss className="btn">Cancel</Modal.Dismiss>
        <button className="btn" onClick={this.click.bind(this)}>Add</button>
    </Modal.Footer>
</Modal>
```

In the `click` routine, the value `this.refs.input` is undefined. Is there a way I can use a `ref` inside the Modal components?

**Comment by jquense** [comment]
`refs` work inside of a modal, but if the modal is closed, that entire leaf of the DOM isn't rendered so the refs don't exist

**Comment by larzconwell** [comment]
You're right. Also it worked after I called setData, so I'm gonna close.

**Comment by mtando** [comment]
I had same issue, @larzconwell  can you pls elaborate what setData is that you called to make it work?
