### ISSUE TITLE
React 15.2.0 warnings

### ISSUE THREAD

**Issue by elmoro666** [jquense/react-bootstrap-modal#20]
After upgrading to React 15.2.0 I am getting the following warnings:

![image](https://cloud.githubusercontent.com/assets/15340253/16683273/3908894a-44ff-11e6-8601-15c6766cc325.png)

Link to react docs:
https://fb.me/react-unknown-prop

**Comment by discomarra** [comment]
+1

**Comment by d-winter** [comment]
+1

**Comment by jquense** [comment]
PR's Welcome!

**Comment by danielmahadi** [comment]
Hi @jquense,
Please review the PR :)

Happy to help with other changes

**Comment by auschmann** [comment]
Hi,

any idea when danielmahadi´s PR will be merged.
react-bbotstrap-modal is the last library that throws the unknown prop warning in my project.
Is there anything i could do to help?

Regards

André
