### ISSUE TITLE
Modals broken due to breaking change in react-overlays dependency

### ISSUE THREAD

**Issue by Pisi-Deff** [jquense/react-bootstrap-modal#28]
When trying to open a modal:
`Uncaught TypeError: Cannot read property 'modals' of undefined`

[Link to breaking code](https://github.com/jquense/react-bootstrap-modal/blob/master/src/Modal.js#L113)
```
return (type) => baseIndex[type] + (zIndexFactor * (BaseModal.manager.modals.length - 1));
```

[Link to change in react-overlays](https://github.com/react-bootstrap/react-overlays/commit/b09cd137a43e79442536f2cbc6fbcff0a749a7e0#diff-3ddc036af206541151e86f03cfc0c0eeL466)
```
-Modal.manager = modalManager;
+Modal.Manager = ModalManager;
```

**Comment by FoxWhite** [comment]
Got this issue too

**Comment by wanjs** [comment]
me, too.

**Comment by wanjs** [comment]
actually, the problem occurs in  the react-overlays.  
`Modal.Manager = ModalManager;`
but, I think it should be this ：
`Modal.Manager = modalManager;`

**Comment by wanjs** [comment]
or 
`const baseModal = new _Modal2.default.Manager();
 return baseIndex[type] + zIndexFactor * (baseModal.modals.length - 1);`

**Comment by wanjs** [comment]
thanks
