### ISSUE TITLE
Cannot read property 'modals' of undefined

### ISSUE THREAD

**Issue by peebles** [jquense/react-bootstrap-modal#32]
I am getting this error in the console:

    Modal.js:136Uncaught TypeError: Cannot read property 'modals' of undefined

Due to the following code:

```javascript
return function (type) {
        return baseIndex[type] + zIndexFactor * (_Modal2.default.manager.modals.length - 1);
};
```

**Comment by peebles** [comment]
I notice the code I have (via npm install) is different than the code in master.  The npm package is at 3.0.0.  Does this need to be bumped?

**Comment by adanarchila** [comment]
I think this was patched here: https://github.com/jquense/react-bootstrap-modal/issues/28 but they didn't build a release :(

**Comment by atis--** [comment]
jquense should make a new release; meanwhile you can use my build if you want:
`npm install --save @atis/react-bootstrap-modal`
`require('@atis/react-bootstrap-modal');`

**Comment by jquense** [comment]
fixed and released
