### ISSUE TITLE
Not showing in bootstrap 3.3.7

### ISSUE THREAD

**Issue by devmetal** [jquense/react-bootstrap-modal#40]
Hi, i use boostrap 3.3.7 and when i set the show property true, the backdrop is showing up, but the modal is not. When i check in developer console, i see the modal style still display: none.

I create a pr for this and the readme example.

**Comment by jquense** [comment]
that sounds like an issue with the css your including? all the modal display bits should be handled by the bootstrap css file

**Comment by devmetal** [comment]
Maybe, but i not rewrite any css class or style. I use pure bootstrap. When i check the modal in inspector i see display: none after i set show property ture. At home i will paste here my example.

**Comment by trajano** [comment]
I wonder if it is the same issue with Bootstrap 4.0.alpha6

**Comment by jquense** [comment]
V4 of bootstrap is not supported at the moment
