### ISSUE TITLE
isMounted is deprecated

### ISSUE THREAD

**Issue by SirAlb3rt** [jquense/react-bootstrap-modal#48]
I'm having this warning every time modal is open.

Warning: Modal: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by jquense** [comment]
PR's welcome!

**Comment by LuciRebecca** [comment]
+1
The issue comes out of react-overlays, but when upgrading to the latest version there are more changes that cause... more issues from things like the [Transition change](https://github.com/react-bootstrap/react-overlays/commit/9f8dd29caa3be9b9259b83e3bc3df84689cf49a0)
