### ISSUE TITLE
Is it possible to have the modal appear beside the clicked button?

### ISSUE THREAD

**Issue by kylemas** [jquense/react-bootstrap-modal#64]
Hi, 

I was wondering if it's possible to have the modal appear beside the clicked button without the background being out of focus? 

Right now, this is what my page looks like and I'd like to have a small modal appear beside the clicked node on the tree but it covers the middle of the screen and makes the background out of focus. 

![Uploading Screen Shot 2019-07-26 at 3.45.52 PM.png…]()
<img width="579" alt="Screen Shot 2019-07-26 at 3 45 54 PM" src="https://user-images.githubusercontent.com/34122775/61985115-874a0b80-afbc-11e9-89a9-806cf04c7782.png">

**Comment by jquense** [comment]
you have to have custom css for this, which isn't part of bootstrap. If you want something more custom i might recommend `react-overlays` which is what we use to build the Modal, it's a lot more flexible and agnostic on styling, but you have to do more work to style it yourself
