### ISSUE TITLE
Is it possible to have the modal appear beside the clicked button?

### ISSUE THREAD

**Issue by kylemas** [jquense/react-bootstrap-modal#65]
Hi, 

I was wondering if it's possible to have the modal appear beside the clicked button without the background being out of focus? 

Right now, this is what my page looks like and I'd like to have a small modal appear beside the clicked node on the tree but it covers the middle of the screen and makes the background out of focus. 

<img width="225" alt="Screen Shot 2019-07-26 at 3 45 52 PM" src="https://user-images.githubusercontent.com/34122775/61985128-9fba2600-afbc-11e9-995f-f102a5e216a1.png">

<img width="579" alt="Screen Shot 2019-07-26 at 3 45 54 PM" src="https://user-images.githubusercontent.com/34122775/61985115-874a0b80-afbc-11e9-89a9-806cf04c7782.png">

**Comment by jquense** [comment]
duplicate #64
