### ISSUE TITLE
Autofocus lost inside this Modal.

### ISSUE THREAD

**Issue by SudoPlz** [jquense/react-bootstrap-modal#7]
I'm trying to autoFocus a username Input inside this modal and I find this impossible.
Does your Modal eat up my autofocus?

How should I do this?

**Comment by danesparza** [comment]
Use the autoFocus attribute on the HTML input element.  It's a polyfill for the HTML5 `autofocus` attribute.  

Example:
`<input className="form-control" id="txtNewAppName" placeholder="Your application name" autoFocus/>`
